CREATE TABLE IF NOT EXISTS canvases (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL UNIQUE,
  name VARCHAR(140) NOT NULL DEFAULT 'Canvas principal',
  elements_json JSON NOT NULL,
  version INT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_canvases_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);
